// Auto-generated from pvm_events_rows.csv
// Boss name -> known drops and pets
export const BOSS_LOOT_TABLE: Record<string, { drops: string[]; pets: string[] }> = {
  "Abhorrent Spectre": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Abyssal Demon": { drops: ["Abyssal Dagger"], pets: [] },
  "Abyssal Sire": { drops: ["Unsired"], pets: [] },
  "Adamant Dragon": { drops: ["Draconic Visage","Dragon Metal Slice"], pets: [] },
  "Agility": { drops: [], pets: ["Giant Squirrel"] },
  "Alchemical Hydra": { drops: ["Hydra Leather","Hydra Tail","Hydra's Claw","Hydra's Eye","Hydra's Fang","Hydra's Heart","Jar Of Chemicals"], pets: ["Ikkle Hydra"] },
  "Amoxliatl": { drops: [], pets: ["Moxi"] },
  "Ancient Wyvern": { drops: ["Wyvern Visage"], pets: [] },
  "Araxxor": { drops: ["Araxyte Fang","Noxious Blade","Noxious Point","Noxious Pommel"], pets: ["Nid"] },
  "Armadylean Guard": { drops: ["Armadyl Helmet"], pets: [] },
  "Artio": { drops: ["Dragon 2h Sword","Dragon Pickaxe","Tyrannical Ring","Voidwaker Hilt"], pets: ["Callisto Cub"] },
  "Azzanadra": { drops: [], pets: ["Lil' Azzanadra"] },
  "Balance Elemental": { drops: [], pets: ["Lil' Elemental"] },
  "Balfrug Kreeyath": { drops: ["Zamorakian Spear"], pets: [] },
  "Barrelchest": { drops: [], pets: ["Brainlet"] },
  "Barrows": { drops: [], pets: ["Pet Ahrim"] },
  "Basilisk Knight": { drops: ["Basilisk Jaw"], pets: [] },
  "Basilisk Sentinel": { drops: ["Basilisk Jaw","Eternal Gem","Imbued Heart"], pets: [] },
  "Black Dragon": { drops: ["Draconic Visage"], pets: [] },
  "Blood Revenant Cyclops": { drops: ["Amulet Of Avarice","Viggora's Chainmace (u)"], pets: [] },
  "Blood Revenant Dark Beast": { drops: ["Thammaron's Sceptre"], pets: [] },
  "Blood Revenant Dragon": { drops: ["Amulet Of Avarice","Thammaron's Sceptre"], pets: [] },
  "Blood Revenant Hellhound": { drops: ["Craw's Bow (u)"], pets: [] },
  "Blood Revenant Imp": { drops: ["Amulet Of Avarice","Thammaron's Sceptre"], pets: [] },
  "Blood Revenant Ork": { drops: ["Craw's Bow (u)"], pets: [] },
  "Blood Revenant Pyrefiend": { drops: ["Amulet Of Avarice"], pets: [] },
  "Bree": { drops: ["Saradomin Sword"], pets: [] },
  "Brutal Black Dragon": { drops: ["Draconic Visage"], pets: [] },
  "Brutal Blue Dragon": { drops: ["Draconic Visage"], pets: [] },
  "Brutus": { drops: [], pets: ["Beef"] },
  "Callisto": { drops: ["Dragon 2h Sword","Dragon Pickaxe","Tyrannical Ring","Voidwaker Hilt"], pets: ["Callisto Cub"] },
  "Calvar'ion": { drops: ["Dragon 2h Sword","Dragon Pickaxe","Ring Of The Gods","Voidwaker Blade"], pets: ["Vet'ion Jr."] },
  "Cave Abomination": { drops: ["Eternal Gem","Imbued Heart","Trinket Of Advanced Weaponry"], pets: [] },
  "Cerberus": { drops: ["Eternal Crystal","Jar Of Souls","Pegasian Crystal","Primordial Crystal","Smouldering Stone","Trinket Of Advanced Weaponry"], pets: ["Hellpuppy"] },
  "Chambers of Xeric: Challenge Mode": { drops: [], pets: ["Olmlet"] },
  "Chambers of Xeric: Normal Mode": { drops: [], pets: ["Olmlet"] },
  "Chaos Elemental": { drops: ["Dragon 2h Sword","Dragon Pickaxe"], pets: ["Pet Chaos Elemental"] },
  "Chaos Fanatic": { drops: ["Malediction Shard 1","Odium Shard 1"], pets: ["Pet Chaos Elemental"] },
  "Choke Devil": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Commander Zilyana": { drops: ["Armadyl Crossbow","Saradomin Hilt","Saradomin Sword","Saradomin's Light","Trinket Of Advanced Weaponry"], pets: ["Pet Zilyana"] },
  "Construction": { drops: [], pets: ["Baba Yaga"] },
  "Corporeal Beast": { drops: ["Arcane Sigil","Elysian Sigil","Holy Elixir","Jar Of Spirits","Spectral Sigil"], pets: ["Pet Dark Core"] },
  "Crazy Archaeologist": { drops: ["Malediction Shard 2","Odium Shard 2"], pets: ["Flying Book"] },
  "Dagannoth Prime": { drops: ["Dragon Axe","Trinket Of Advanced Weaponry"], pets: ["Pet Dagannoth Prime"] },
  "Dagannoth Rex": { drops: ["Dragon Axe","Trinket Of Advanced Weaponry"], pets: ["Pet Dagannoth Rex"] },
  "Dagannoth Supreme": { drops: ["Dragon Axe","Trinket Of Advanced Weaponry"], pets: ["Pet Dagannoth Supreme"] },
  "Demonic Gorilla": { drops: ["Ballista Limbs","Ballista Spring","Monkey Tail","Zenyte Shard"], pets: [] },
  "Deranged Archaeologist": { drops: [], pets: ["Flying Book"] },
  "Derwen": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Dharok The Wretched": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Dominion Tower": { drops: [], pets: ["Lil' Roc"] },
  "Drake": { drops: ["Drake's Claw","Drake's Tooth"], pets: [] },
  "Dreadborn Araxyte": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Dreadborn Araxyte 1 Add Reaction": { drops: ["Eternal Gem"], pets: [] },
  "Duke Sucellus": { drops: ["Chromium Ingot","Eye Of The Duke","Magus Vestige","Virtus Mask","Virtus Robe Bottom","Virtus Robe Top"], pets: ["Baron"] },
  "Durial321": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Dusk": { drops: ["Black Tourmaline Core","Jar Of Stone"], pets: [] },
  "Farming": { drops: [], pets: ["Tangleroot"] },
  "Fishing": { drops: [], pets: ["Heron"] },
  "Flaming Pyrelord": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Flight Kilisa": { drops: ["Armadyl Chainskirt","Armadyl Chestplate","Armadyl Helmet"], pets: [] },
  "Flockleader Geerin": { drops: ["Armadyl Chainskirt","Armadyl Chestplate","Armadyl Helmet"], pets: [] },
  "Fragment Of Seren": { drops: ["Crystal Crown","Seren's Tome"], pets: ["Serenity"] },
  "Frost Dragon": { drops: ["Draconic Visage"], pets: [] },
  "Galvek": { drops: ["Armadyl Godsword","Blessed Spirit Shield","Corrupted Gem","Dragonfire Shield","Imbued Heart","Occult Necklace","Staff Of Light","Toxic Staff Of The Dead"], pets: ["Galvek Jr"] },
  "Gauntlet (Corrupted)": { drops: [], pets: ["Youngllef"] },
  "Gauntlet (Normal)": { drops: [], pets: ["Youngllef"] },
  "Gauntlet (corrupted)": { drops: [], pets: ["Youngllef"] },
  "Gauntlet (normal)": { drops: [], pets: ["Youngllef"] },
  "General Graardor": { drops: ["Bandos Chestplate","Bandos Hilt","Bandos Tassets","Trinket Of Advanced Weaponry"], pets: ["Pet General Graardor"] },
  "Giant Goblin": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Giant mole": { drops: [], pets: ["Baby Mole"] },
  "Greater Abyssal Demon": { drops: ["Abyssal Dagger","Eternal Gem","Imbued Heart","Trinket Of Advanced Weaponry"], pets: [] },
  "Grotesque Guardians": { drops: [], pets: ["Noon"] },
  "Growler": { drops: ["Saradomin Sword"], pets: [] },
  "Guardian Drake": { drops: ["Drake's Claw","Drake's Tooth","Imbued Heart"], pets: [] },
  "Hellhound": { drops: ["Smouldering Stone"], pets: [] },
  "Herbiboar": { drops: [], pets: ["Herbi"] },
  "Herblore": { drops: [], pets: ["Herbi"] },
  "Hunter": { drops: [], pets: ["Baby Chinchompa","Quetzin"] },
  "Hydra": { drops: ["Hydra Tail","Hydra's Eye","Hydra's Fang","Hydra's Heart"], pets: [] },
  "Inferno": { drops: [], pets: ["Jal-nib-rek"] },
  "Insatiable Bloodveld": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Insatiable Mutated Bloodveld": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Iorwerth Warrior": { drops: ["Enhanced Crystal Teleport Seed"], pets: [] },
  "Iron Dragon": { drops: ["Draconic Visage"], pets: [] },
  "Jaguar Warrior": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Jal-imkot": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Justiciar Zachariah": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "K'ril Tsutsaroth": { drops: ["Staff Of The Dead","Trinket Of Advanced Weaponry","Zamorak Hilt","Zamorakian Spear"], pets: ["Pet K'ril Tsutsaroth"] },
  "Kalphite Queen": { drops: ["Dragon 2h Sword","Dragon Pickaxe","Jar Of Sand"], pets: ["Kalphite Princess"] },
  "King Black Dragon": { drops: ["Draconic Visage","Dragon Pickaxe","Trinket Of Advanced Weaponry"], pets: ["Prince Black Dragon"] },
  "King Kurask": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Kraken": { drops: ["Jar Of Dirt"], pets: ["Pet Kraken"] },
  "Kree'arra": { drops: ["Armadyl Chainskirt","Armadyl Chestplate","Armadyl Helmet","Armadyl Hilt","Trinket Of Advanced Weaponry"], pets: ["Pet Kree'arra"] },
  "Lava Dragon": { drops: ["Draconic Visage"], pets: [] },
  "Lizardman Shaman": { drops: ["Dragon Warhammer"], pets: [] },
  "Long-tailed Wyvern": { drops: ["Wyvern Visage"], pets: [] },
  "Magic Mark": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Malevolent Mage": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Marble Gargoyle": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Mining": { drops: [], pets: ["Rock Golem"] },
  "Mithril Dragon": { drops: ["Draconic Visage","Dragon Full Helm"], pets: [] },
  "Mutant Tarn": { drops: [], pets: ["Mutant Tarn"] },
  "Nechryarch": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Nex": { drops: ["Ancient Hilt","Ice Crystal","Nihil Horn","Torva Full Helm (damaged)","Torva Platebody (damaged)","Torva Platelegs (damaged)","Zaryte Vambraces"], pets: ["Nexling"] },
  "Night Beast": { drops: ["Eternal Gem","Imbued Heart","Trinket Of Advanced Weaponry"], pets: [] },
  "Nuclear Smoke Devil": { drops: ["Eternal Gem","Imbued Heart","Occult Necklace"], pets: [] },
  "Phantom Muspah": { drops: ["Ancient Icon","Venator Shard"], pets: ["Muphin"] },
  "Phosani's Nightmare": { drops: ["Eldritch Orb","Harmonised Orb","Inquisitor's Great Helm","Inquisitor's Hauberk","Inquisitor's Mace","Inquisitor's Plateskirt","Jar Of Dreams","Nightmare Staff","Volatile Orb"], pets: ["Little Nightmare"] },
  "Porazdir": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Prayer": { drops: [], pets: ["Holy Owl"] },
  "Prifddinas Rabbit": { drops: [], pets: ["Blood Bunny"] },
  "Ranging Ro": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Repugnant Spectre": { drops: ["Eternal Gem"], pets: [] },
  "Revenant Cyclops": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Dark Beast": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Demon": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Dragon": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Goblin": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Hellhound": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Hobgoblin": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Imp": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Knight": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Maledictus": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Ork": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Revenant Pyrefiend": { drops: ["Amulet Of Avarice","Craw's Bow (u)","Thammaron's Sceptre","Viggora's Chainmace (u)"], pets: [] },
  "Royal Titans": { drops: [], pets: ["Bran"] },
  "Rune Dragon": { drops: ["Draconic Visage","Dragon Metal Lump"], pets: [] },
  "Runecraft": { drops: [], pets: ["Rift Guardian"] },
  "Sarachnis": { drops: ["Jar Of Eyes","Sarachnis Cudgel"], pets: ["Sraracha"] },
  "Scorpia": { drops: ["Dragon 2h Sword","Malediction Shard 3","Odium Shard 3"], pets: ["Scorpia's Offspring"] },
  "Screaming Banshee": { drops: ["Eternal Gem"], pets: [] },
  "Scurrius": { drops: [], pets: ["Scurry"] },
  "Sea Kraken": { drops: ["Exotic Fish","Jar Of Dirt"], pets: ["Pet Kraken"] },
  "Sergeant Grimspike": { drops: ["Bandos Chestplate","Bandos Tassets"], pets: [] },
  "Sergeant Steelwill": { drops: ["Bandos Chestplate","Bandos Tassets"], pets: [] },
  "Sergeant Strongstack": { drops: ["Bandos Chestplate","Bandos Tassets"], pets: [] },
  "Shadow Wyrm": { drops: ["Dragon Harpoon","Dragon Sword","Eternal Gem","Imbued Heart"], pets: [] },
  "Shellbane Gryphon": { drops: ["Jar Of Feathers"], pets: ["Gull"] },
  "Skeletal Wyvern": { drops: ["Draconic Visage"], pets: [] },
  "Skotizo": { drops: ["Jar of darkness","Uncut Onyx"], pets: ["Skotos"] },
  "Smithing": { drops: [], pets: ["Smith'ers"] },
  "Smoke Devil": { drops: ["Occult Necklace"], pets: [] },
  "Spiked Turoth": { drops: ["Eternal Gem"], pets: [] },
  "Spindel": { drops: ["Dragon 2h Sword","Dragon Pickaxe","Fangs Of Venenatis","Treasonous Ring","Voidwaker Gem"], pets: ["Venenatis Spiderling"] },
  "Spitting Wyvern": { drops: ["Wyvern Visage"], pets: [] },
  "Starlight": { drops: ["Saradomin Sword"], pets: [] },
  "Steel Dragon": { drops: ["Draconic Visage"], pets: [] },
  "Sulphur Lizard": { drops: ["Trinket Of Advanced Weaponry"], pets: [] },
  "Taloned Wyvern": { drops: ["Wyvern Visage"], pets: [] },
  "Tekton": { drops: ["Onyx"], pets: [] },
  "Tekton 1 Add Reaction": { drops: ["Onyx"], pets: [] },
  "Tempoross": { drops: [], pets: ["Tiny Tempor"] },
  "The Hueycoatl": { drops: ["Dragon Hunter Wand"], pets: ["Huberte"] },
  "The Leviathan": { drops: ["Chromium Ingot","Leviathan's Lure","Venator Vestige","Virtus Mask","Virtus Robe Bottom","Virtus Robe Top"], pets: ["Lil'viathan"] },
  "The Nightmare": { drops: ["Eldritch Orb","Harmonised Orb","Inquisitor's Great Helm","Inquisitor's Hauberk","Inquisitor's Mace","Inquisitor's Plateskirt","Jar Of Dreams","Nightmare Staff","Volatile Orb"], pets: ["Little Nightmare"] },
  "The Whisperer": { drops: ["Bellator Vestige","Chromium Ingot","Siren's Staff","Virtus Mask","Virtus Robe Bottom","Virtus Robe Top"], pets: ["Wisp"] },
  "Theatre of Blood: Hard Mode": { drops: [], pets: ["Lil' Zik"] },
  "Theatre of Blood: Normal Mode": { drops: [], pets: ["Lil' Zik"] },
  "Thermonuclear Smoke Devil": { drops: ["Jar Of Smoke","Occult Necklace","Smoke Battlestaff"], pets: ["Pet Smoke Devil"] },
  "Thieving": { drops: [], pets: ["Guardian Mummy","Rocky"] },
  "Tombs of Amascut: Entry Mode": { drops: [], pets: ["Tumeken's Guardian"] },
  "Tombs of Amascut: Expert Mode": { drops: [], pets: ["Tumeken's Guardian"] },
  "Tombs of Amascut: Normal Mode": { drops: [], pets: ["Tumeken's Guardian"] },
  "Tormented Demon": { drops: ["Burning Claw","Tormented Synapse"], pets: [] },
  "Tortured Gorilla": { drops: ["Ballista Limbs","Ballista Spring","Zenyte Shard"], pets: [] },
  "Tstanon Karlak": { drops: ["Zamorakian Spear"], pets: [] },
  "Tztok-jad": { drops: ["Trinket Of Advanced Weaponry"], pets: ["Tzrek-jad"] },
  "Vanstrom Klause": { drops: ["Blood Shard"], pets: ["Acidic Bloodveld"] },
  "Vardorvis": { drops: ["Chromium Ingot","Executioner's Axe Head","Ultor Vestige","Virtus Mask","Virtus Robe Bottom","Virtus Robe Top"], pets: ["Butch"] },
  "Venenatis": { drops: ["Dragon 2h Sword","Dragon Pickaxe","Fangs Of Venenatis","Treasonous Ring","Voidwaker Gem"], pets: ["Venenatis Spiderling"] },
  "Vet'ion": { drops: ["Dragon 2h Sword","Dragon Pickaxe","Ring Of The Gods","Voidwaker Blade"], pets: ["Vet'ion Jr."] },
  "Vitreous Jelly": { drops: ["Eternal Gem","Imbued Heart"], pets: [] },
  "Vitreous Warped Jelly": { drops: ["Imbued Heart","Trinket Of Advanced Weaponry"], pets: [] },
  "Vorkath": { drops: ["Draconic Visage","Dragonbone Necklace","Jar Of Decay","Skeletal Visage"], pets: ["Vorki"] },
  "Vyrewatch Sentinel": { drops: ["Blood Shard"], pets: [] },
  "Wildy Warrior": { drops: ["Armadyl Godsword","Blessed Spirit Shield","Craw's Bow (u)","Dragonfire Shield","Imbued Heart","Occult Necklace","Staff Of Light","Thammaron's Sceptre","Toxic Staff Of The Dead","Viggora's Chainmace (u)"], pets: [] },
  "Wildy Warrior 1 Add Reaction": { drops: ["Thammaron's Sceptre"], pets: [] },
  "Wingman Skree": { drops: ["Armadyl Chainskirt","Armadyl Chestplate","Armadyl Helmet"], pets: [] },
  "Wintertodt": { drops: [], pets: ["Phoenix"] },
  "Woodcutting": { drops: [], pets: ["Beaver"] },
  "Wyrm": { drops: ["Dragon Harpoon","Dragon Sword"], pets: [] },
  "Xamphur": { drops: ["Book Of The Dead"], pets: [] },
  "Yama": { drops: ["Oathplate Chest","Oathplate Helm","Oathplate Legs","Purifying Sigil","Soulflame Horn"], pets: ["Yami"] },
  "Zakl'n Gritch": { drops: ["Zamorakian Spear"], pets: [] },
  "Zalcano": { drops: ["Uncut Onyx"], pets: ["Smolcano"] },
  "Zulrah": { drops: ["Jar Of Swamp","Magic Fang","Magma Mutagen","Serpentine Visage","Tanzanite Fang","Tanzanite Mutagen","Toxic Dust","Trailblazer Reloaded Blowpipe Ornament Kit","Uncut Onyx"], pets: ["Pet Snakeling"] }
};

export function getBossLoot(bossName: string): { drops: string[]; pets: string[] } {
  return BOSS_LOOT_TABLE[bossName] ?? { drops: [], pets: [] };
}
